GET http://localhost:8000/user

###

POST http://localhost:8000/user
Content-Type: application/json

{
    "firstname": "Biboy",
    "lastname": "Langomez",
    "address": "Cebu",
    "postcode": "6000",
    "contact": "09162364559*",
    "email": "marlzjrjr@gmail.com",
    "username": "marlzjr466",
    "password": "mypassword"
}

###

DELETE http://localhost:8000/user/2
Content-Type: application/json

###

PUT http://localhost:8000/user/2
Content-Type: application/json

{
    "firstname": "Mario",
    "lastname": "Langomez Jr",
    "address": "Cebu",
    "postcode": "6000",
    "contact": "09162364559",
    "email": "marlzjrjr@gmail.com",
    "username": "marlzjr466",
    "password": "pass123"
}

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
    "username": "marlzjr466",
    "password": "mypassword"
}
